version: "3"

services:
    mongo:
      image: mongo
      ports:
        - "27017:27017"
    mongo-restore:
      image: collabcode/db-restore
      restart: on-failure
      environment:
        - MONGODB_HOST=mongo
        - MONGODB_PORT=27017
      volumes:
        - <REPLACE-WITH-YOUR-DUMP-FOLDER>:/dump
      depends_on:
        - mongo
networks:
  db:
